version: "3.8"

services:
  backend:
    container_name: pokemon-backend
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development

  frontend:
    container_name: pokemon-frontend
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
